#!/bin/bash

export AWS_TF_AUTHOR="ihanyouqing@gmail.com"

export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}"
export AWS_SESSION_TOKEN=""
